#!/bin/sh
echo "Backing up iTunes..."
# All the delete has ever brought me is grief. Let Time Machine handle those.
#echo "rsync -av --delete --ignore-existing /Users/quintis/Music/iTunes/ /Volumes/Music/iTunes"
echo "rsync -av --ignore-existing /Users/quintis/Music/iTunes/ /Volumes/Music/iTunes"
rsync -av --ignore-existing /Users/quintis/Music/iTunes/ /Volumes/Music/iTunes
