#!/bin/bash

devices() {
  ifconfig | grep -E "^en\d{1}" | awk '{print $1}' | tr -d ':'
}

for device in `devices`; do
  echo "$device:$(ifconfig $device | grep 'inet ' | awk '{print $2}')"
done | grep -vE ":$"
