#!/usr/bin/env python

#* vim: set filetype=python

import os
from termcolor import colored
from subprocess import check_output

home = os.path.expanduser('~')
paths = []
paths.append(os.path.join(home, 'source'))
paths.append(os.path.join(home, 'bin'))

longest_dir = 1

for path in paths:
    for root, dirs, files in os.walk(path):
      if ".git" in dirs:
          os.chdir(root)
          if "working directory clean" in check_output(["git", "status"]):
              color = "green"
          else:
              color = "red"
          
          print "%-5s %-35s %s" % (colored(u"\u2717", color), os.getcwd().split('/')[-1], os.getcwd())

